apiVersion: apps/v1
kind: Deployment
metadata:
  name: Capstone-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Capstone-app
  template:
    metadata:
      labels:
        app: Capstone-app
    spec:
      containers:
      - name: fox-app-container
        image: tomkugelman/capstone-flask
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Capstone-service
spec:
  selector:
    app: Capstone-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http